### ISSUE TITLE
can't start a repl in 0.4.5

### ISSUE THREAD

**Issue by lerouxrgd** [weavejester/duct#19]
Looks like [duct/figwheel-component "0.3.0"] is causing some issue.
I simply tried:

```
lein new duct test-duct +cljs +example
cd test-duct
lein setup
lein repl
```

And then I get this error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalStateException: var: #'clojure.tools.nrepl.middleware.interruptible-eval/queue-eval is not public, compiling:(cemerick/piggieback.clj:240:3)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6179)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)                                                                     
        at clojure.lang.Compiler.access$300(Compiler.java:38)                                                                    
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)                                                         
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)                                                                  
        at clojure.lang.Compiler.analyze(Compiler.java:6524)                                                                     
        at clojure.lang.Compiler.analyze(Compiler.java:6485)                                                                     
        at clojure.lang.Compiler.eval(Compiler.java:6786)                                                                        
        at clojure.lang.Compiler.load(Compiler.java:7227)                                                                        
        at clojure.lang.RT.loadResourceScript(RT.java:371)                                                                       
        at clojure.lang.RT.loadResourceScript(RT.java:362)                                                                       
        at clojure.lang.RT.load(RT.java:446)                                                                                     
        at clojure.lang.RT.load(RT.java:412)                                                                                     
        at clojure.core$load$fn__5448.invoke(core.clj:5866)                                                                      
        at clojure.core$load.doInvoke(core.clj:5865)                                                                             
        at clojure.lang.RestFn.invoke(RestFn.java:408)                                                                           
        at clojure.core$load_one.invoke(core.clj:5671)                                                                           
        at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)                                                                  
        at clojure.core$load_lib.doInvoke(core.clj:5710)                                                                         
        at clojure.lang.RestFn.applyTo(RestFn.java:142)                                                                          
        at clojure.core$apply.invoke(core.clj:632)                                                                               
        at clojure.core$load_libs.doInvoke(core.clj:5749)                                                                        
        at clojure.lang.RestFn.applyTo(RestFn.java:137)                                                                          
        at clojure.core$apply.invoke(core.clj:632)                                                                               
        at clojure.core$require.doInvoke(core.clj:5832)                                                                          
        at clojure.lang.RestFn.invoke(RestFn.java:1289)                                                                          
        at duct.component.figwheel$eval3668$loading__5340__auto____3669.invoke(figwheel.clj:1)                                   
        at duct.component.figwheel$eval3668.invoke(figwheel.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6771)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:362)
        at clojure.lang.RT.load(RT.java:446)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5448.invoke(core.clj:5866)
        at clojure.core$load.doInvoke(core.clj:5865)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5671)
        at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
        at clojure.core$load_lib.doInvoke(core.clj:5710)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$load_libs.doInvoke(core.clj:5749)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$require.doInvoke(core.clj:5832)
        at clojure.lang.RestFn.invoke(RestFn.java:1096)
        at user$eval3$loading__5340__auto____4.invoke(user.clj:1)
        at user$eval3.invoke(user.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6771)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        at clojure.lang.RT.loadResourceScript(RT.java:371)
        at clojure.lang.RT.loadResourceScript(RT.java:358)
        at clojure.lang.RT.maybeLoadResourceScript(RT.java:354)
        at clojure.lang.RT.doInit(RT.java:468)
        at clojure.lang.RT.<clinit>(RT.java:330)
        ... 1 more
Caused by: java.lang.IllegalStateException: var: #'clojure.tools.nrepl.middleware.interruptible-eval/queue-eval is not public
        at clojure.lang.Compiler.isInline(Compiler.java:6592)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6716)
        ... 73 more
Exception in thread "Thread-4" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
        at clojure.core$ex_info.invoke(core.clj:4593)
        at leiningen.core.eval$fn__5830.invoke(eval.clj:255)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
        at leiningen.repl$server$fn__11848.invoke(repl.clj:243)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:630)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:634)
        at clojure.core$bound_fn_STAR_$fn__4439.doInvoke(core.clj:1890)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by weavejester** [comment]
What version of Leiningen are you using? This bug doesn't occur for me when running 2.5.3.

Before you upgrade, does the issue go away if you add an explicit dependency to nrepl in your dev dependencies? i.e.

```clojure
[org.clojure/tools.nrepl "0.2.10"]
```

**Comment by lerouxrgd** [comment]
I am using Leiningen 2.5.3 but I realised I was using an old  tools.nrepl (0.2.7)
I upgraded it to 0.2.10 and it works fine !
Thank you for the help.
